server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://121.199.13.81:3306/sampledb
    username: root
    password: Zn19981130.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://servre1:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: coupon-template
    groupId: coupon-service
    artifactId: template
    version: 1.0-SNAPSHOT


logging:
  level:
    com.coupon: debug
